#自定义数据库连接配置
my:
  datasource:
    url: @application_mybatis.datasource_url@
    username: @application_mybatis.datasource_user_name@
    password: @application_mybatis.datasource_password@
    driver-class-name: @application_mybatis.datasource_driver_class_name@
  mybatis:
    type-aliases-package: com.example.demo.mapper.entity
    mapper-locations: classpath:mybatis/mapper/*.xml